USE [master]
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'Diary')
	DROP DATABASE [Diary]
CREATE DATABASE [Diary]
GO

USE [Diary]
GO

CREATE TABLE [User] (
	[idUser] BIGINT NOT NULL IDENTITY(1,1),
	[Login] NVARCHAR(16) NOT NULL UNIQUE,
	[Password] NVARCHAR(16) NOT NULL,
	[Mail] NVARCHAR(31) NOT NULL UNIQUE,
	[Birthday] DATE NOT NULL,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [idUser] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

CREATE TABLE [Task] (
	[idTask] BIGINT NOT NULL IDENTITY(1,1),
	[NameTask] NVARCHAR(127) NOT NULL,
	[IsComplete] BIT NULL DEFAULT 0,
	[DateTask] DATE NOT NULL,
  CONSTRAINT [PK_TASK] PRIMARY KEY CLUSTERED
  (
  [idTask] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

CREATE TABLE [UserTask] (
	[fk_idUser] BIGINT NOT NULL,
	[fk_idTask] BIGINT NOT NULL
)
GO


ALTER TABLE [UserTask] WITH CHECK ADD CONSTRAINT [UserTask_fk0] FOREIGN KEY ([fk_idUser]) REFERENCES [User]([idUser])
ON UPDATE CASCADE
GO
ALTER TABLE [UserTask] CHECK CONSTRAINT [UserTask_fk0]
GO
ALTER TABLE [UserTask] WITH CHECK ADD CONSTRAINT [UserTask_fk1] FOREIGN KEY ([fk_idTask]) REFERENCES [Task]([idTask])
ON UPDATE CASCADE
GO
ALTER TABLE [UserTask] CHECK CONSTRAINT [UserTask_fk1]
GO



